<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiteSelectorsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('site_selectors')->insert([
            [
                'site' => 'topcv',
                'page_type' => 'search_form',
                'element_key' => 'keyword_input',
                'selector_type' => 'id',
                'selector_value' => 'keyword',
                'description' => 'Ô input từ khóa tìm kiếm',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'search_form',
                'element_key' => 'city_dropdown',
                'selector_type' => 'id',
                'selector_value' => 'select2-city-container',
                'description' => 'Dropdown chọn tỉnh/thành phố',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'search_form',
                'element_key' => 'position_dropdown',
                'selector_type' => 'id',
                'selector_value' => 'select2-position-container',
                'description' => 'Dropdown chọn cấp bậc',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'search_form',
                'element_key' => 'salary_dropdown',
                'selector_type' => 'id',
                'selector_value' => 'select2-salary-container',
                'description' => 'Dropdown chọn mức lương',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'search_form',
                'element_key' => 'search_button',
                'selector_type' => 'xpath',
                'selector_value' => '//form[@id=\'frm-search-job\']//button[@type=\'submit\']',
                'description' => 'Nút tìm kiếm',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_list',
                'element_key' => 'job_card_container',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="main"]/div[1]/div[3]/div[3]/div[1]/div[1]/div',
                'description' => 'Container chứa các job card (dùng để loop)',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_list',
                'element_key' => 'job_title_link',
                'selector_type' => 'xpath',
                'selector_value' => '/div/div[2]/div[2]/h3/a',
                'description' => 'Link tiêu đề job (relative từ card)',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_list',
                'element_key' => 'next_page_button',
                'selector_type' => 'xpath',
                'selector_value' => '//a[contains(@class, \'next\') or contains(text(), \'Trang tiếp theo\')]',
                'description' => 'Nút chuyển trang tiếp theo',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_detail',
                'element_key' => 'title',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="header-job-info"]/h1',
                'description' => 'Tiêu đề công việc',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_detail',
                'element_key' => 'salary',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="header-job-info"]/div[1]/div[1]/div[2]/div[2]',
                'description' => 'Mức lương',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_detail',
                'element_key' => 'location',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="header-job-info"]/div[1]/div[2]/div[2]/div[2]',
                'description' => 'Địa điểm',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_detail',
                'element_key' => 'experience',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="job-detail-info-experience"]/div[2]/div[2]',
                'description' => 'Yêu cầu kinh nghiệm',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_detail',
                'element_key' => 'job_description',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="box-job-information-detail"]/div[3]/div[1]/div/div[1]/div',
                'description' => 'Mô tả công việc',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_detail',
                'element_key' => 'requirements',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="box-job-information-detail"]/div[3]/div[1]/div/div[2]/div',
                'description' => 'Yêu cầu công việc',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_detail',
                'element_key' => 'expand_button',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="box-job-information-detail"]/div[4]/button',
                'description' => 'Nút mở rộng chi tiết',
                'is_active' => true,
                'version' => 1,
            ],
            [
                'site' => 'topcv',
                'page_type' => 'job_detail',
                'element_key' => 'checkbox_agree',
                'selector_type' => 'xpath',
                'selector_value' => '//*[@id="SoGDz7"]/div/label/input',
                'description' => 'Checkbox đồng ý (nếu có)',
                'is_active' => true,
                'version' => 1,
            ],
        ]);
    }
}
